export const studies = [
  { id: 'cinematic', number: '01', name: 'After dark', style: 'Cinematic', tag: 'VOLUME / CHAR / ATMOSPHERE',
    description: 'Hot, translucent flame against cool night air. Rough bark, glowing fissures and a slow column of smoke.',
    color: '#ffaf68', background: '#111510', ground: '#242823', smoke: '#77817e', bloom: .42, exposure: 1.08, seed: 42,
    camera: [6.7, 4.0, 8.2], target: [0, 2.0, 0], flameScale: 1, mode: 0 },
  { id: 'faceted', number: '02', name: 'Wild geometry', style: 'Faceted', tag: 'PLANES / PIGMENT / SHADOW',
    description: 'A sculpted miniature: angular flames, cut-stone coals and billowing smoke built from broad, colored facets.',
    color: '#ffbc67', background: '#202a36', ground: '#465361', smoke: '#657a8b', bloom: .2, exposure: 1.1, seed: 96,
    camera: [6.7, 5.7, 8.2], target: [0, 1.9, 0], flameScale: 1, mode: 1 },
  { id: 'ink', number: '03', name: 'Field notes', style: 'Ink & wash', tag: 'CONTOUR / GRAIN / WASH',
    description: 'Charcoal contours and warm pools of color on paper. Layered fire, hatched wood and loose curls of smoke.',
    color: '#b74e2b', background: '#e8e4d9', ground: '#b9b3a7', smoke: '#89867c', bloom: .04, exposure: 1.0, seed: 22,
    camera: [6.7, 4.6, 8.2], target: [0, 1.9, 0], flameScale: 1, mode: 2 },
  { id: 'glass', number: '04', name: 'Liquid light', style: 'Luminous glass', tag: 'RIBBONS / REFLECTION / BLOOM',
    description: 'A fire cast in light. Smooth amber ribbons wrap obsidian logs beneath silver smoke and suspended sparks.',
    color: '#f7b977', background: '#0e1720', ground: '#14212b', smoke: '#819cb4', bloom: .6, exposure: 1, seed: 11,
    camera: [6.7, 4.0, 8.2], target: [0, 1.9, 0], flameScale: 1, mode: 3 },
  { id: 'embers', number: '05', name: 'The last heat', style: 'Ember study', tag: 'ASH / COPPER / BLUE FLAME',
    description: 'A lower fire with its inner life exposed: white ash, incandescent charcoal, blue roots and tiny burning branches.',
    color: '#ec8655', background: '#17130f', ground: '#302922', smoke: '#8c8982', bloom: .35, exposure: 1.2, seed: 73,
    camera: [5.7, 4.3, 7], target: [0, 1.2, 0], flameScale: .56, mode: 4 },
  { id: 'living-contours', number: '07', name: 'Living contours', style: 'Folded flame', collection: 'refinements',
    tag: 'INK & WASH / LUMINOUS FOLDS',
    description: 'Luminous folds over an earthen clearing. Follow each log from whole wood through flame, glowing char and quiet ash.',
    color: '#ffc27d', background: '#111510', ground: '#242823', smoke: '#77817e', bloom: .42, exposure: 1.08, seed: 22,
    camera: [6.7, 4.3, 8.2], target: [0, 1.95, 0], flameScale: 1, mode: 5, solidMode: 2, fireVariant: 1, animated: true },
  { id: 'wild-draft', number: '08', name: 'Wild draft', style: 'Turbulent flame', collection: 'refinements',
    tag: 'INK & WASH / CURLS & WISPS',
    description: 'A wind-touched fire, from first heat to the last coal. Whole logs catch, char and settle into the dirt as the fire lives out its cycle.',
    color: '#f5a665', background: '#111510', ground: '#242823', smoke: '#77817e', bloom: .42, exposure: 1.08, seed: 22,
    camera: [6.7, 4.3, 8.2], target: [0, 1.95, 0], flameScale: 1, mode: 5, solidMode: 2, fireVariant: 2, animated: true },
];
